ref_video_path: /data/zhangzijian/MotionClone/reference_videos/sample_white_tiger.mp4 
# ref_video_path: /data/zhangzijian/video_data/camera_motion_val/camera_motion_val/0845841350913fc1.mp4
ref_prompt: ""
ref_feat: "/data/zhangzijian/MotionClone/val_feat/tmp/sample-white-tiger.pt"
# ref_feat: "/data2/zhangzijian/MotionClone/camera_motion_val/0845841350913fc1.pt"
prompts:
  # - "A dense forest with sunlight filtering through the trees."
  # - "A misty waterfall cascading into a clear pool below."
  # - "van, running, in the desert"
  # - "Lamborghini, running, on the beach"
  # - "cat, turning its head, in the desert"
  # - "bear, turning its head, in the forest"
  # - "boy, turning its head, in the room"
  # - "iron man, on the moon"
  # - "spider man, in the city"
  # - "robot, in the desert"
  # - "hunter, in the forest"
  # - "blonde, on the beach"
  # - "man, move his head, in the room"
  # - "bear, move its head, in the snow"
  # - "cat walking on the beach."
  # - "dog walking in the desert"
  # - "horse walking in the desert"
  - "lion walking in the desert"
  # - "duck walking on the beach"
  # - "car, in the desert"
  # - "van, on the beach"
  # - "Lamborghini, in the desert"
  # - "train, in the forest"
  # - "horse, in the desert"