# ref_video_path: /data/zhangzijian/MotionClone/reference_videos/sample_white_tiger.mp4 
ref_video_path: /data/zhangzijian/video_data/square_videos/head4.mp4
ref_prompt: ""
ref_feat: "/data2/zhangzijian/MotionClone/val_ref_feat/head4.pt"
# ref_feat: "/data/zhangzijian/MotionClone/val_feat/tmp/sample-white-tiger.pt"
prompts:
  # - "A rocky cliff overlooking a vast ocean horizon."
  # - "A ceramic vase filled with fresh flowers on a windowsill."
  # - "the overview of Triumphal Arch"
  # - "van, running, in the desert"
  # - "Lamborghini, running, on the beach"
  # - "cat, turning its head, in the desert"
  # - "bear, turning its head, in the forest"
  # - "boy, turning its head, in the room"
  # - "iron man, on the moon"
  # - "spider man, in the city"
  # - "robot, in the desert"
  # - "hunter, in the forest"
  # - "blonde, on the beach"
  # - "man, move his head, in the room"
  # - "bear, move its head, in the snow"
  # - "Duck raises its head"
  - "blonde, move head, in the desert"
  # - "cat walking on the beach."
  # - "dog walking in the desert"
  # - "horse walking in the desert"
  # - "tiger walking in the snow"
  # - "duck walking on the beach"
  # - "car, in the desert"
  # - "van, on the beach"
  # - "Lamborghini, in the desert"
  # - "train, in the forest"
  # - "horse, in the desert"