video_path: data/car_turn
save_dir: data/car_turn/ddim_latents
max_number_of_frames: 16

n_timesteps: 999
prompt: Amazing quality, masterpiece, A car driving on the road
negative_prompt: ""
save_ddim_reconstruction: False